// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn-zmIBnGdj9A6GXwTJVyTdHT6TlzRffc',
    appId: '1:454396613012:web:0ef03870293dbde14ebf81',
    messagingSenderId: '454396613012',
    projectId: 'auth-e6c75',
    authDomain: 'auth-e6c75.firebaseapp.com',
    storageBucket: 'auth-e6c75.appspot.com',
    measurementId: 'G-BYQX96GDVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeUTuBnABbP3vZkvxUhxQqnAwKjUaatFQ',
    appId: '1:454396613012:android:a15d43644f8456de4ebf81',
    messagingSenderId: '454396613012',
    projectId: 'auth-e6c75',
    storageBucket: 'auth-e6c75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmgaZ0MOcDfn5vs-sugK54aV6heuqZCtw',
    appId: '1:454396613012:ios:9ee26db3286755da4ebf81',
    messagingSenderId: '454396613012',
    projectId: 'auth-e6c75',
    storageBucket: 'auth-e6c75.appspot.com',
    iosBundleId: 'com.android.application.authh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmgaZ0MOcDfn5vs-sugK54aV6heuqZCtw',
    appId: '1:454396613012:ios:9ee26db3286755da4ebf81',
    messagingSenderId: '454396613012',
    projectId: 'auth-e6c75',
    storageBucket: 'auth-e6c75.appspot.com',
    iosBundleId: 'com.android.application.authh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn-zmIBnGdj9A6GXwTJVyTdHT6TlzRffc',
    appId: '1:454396613012:web:297d4f89aee71bf54ebf81',
    messagingSenderId: '454396613012',
    projectId: 'auth-e6c75',
    authDomain: 'auth-e6c75.firebaseapp.com',
    storageBucket: 'auth-e6c75.appspot.com',
    measurementId: 'G-Z92P5KBZDJ',
  );
}
